config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root to: "posts#index"
  resources :posts do
    resources :comments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  broadcasts_to :post
  validates_presence_of :content, :user_id

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: %i[ show edit destroy update create ]
  before_action :set_comment, only: %i[ destroy ]

  # GET /comments or /comments.json
 
  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @post.comments.create! comment_params
    redirect_to @post
  end

  
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    puts "destroyed dfserewrewr"
    @comment.destroy!

    respond_to do |format|
      format.html { redirect_to post_path(@post.id), notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  private
  def set_post
    @post = Post.find(params[:post_id])
  end

  # PATCH/PUT /comments/1 or /comments/1.json

  # DELETE /comments/1 or /comments/1.json

  private
    # Use callbacks to share common setup or constraints between actions.

  def comment_params
    params.required(:comment).permit(:content, :user_id)
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">

  <div class="text-stone-900 flex gap-10 my-[10px]">
    <%= comment.content %>

    <span class="italic text-slate-600 ml-[15px]"><%= comment.user.email  %></span>

    <% if user_signed_in? && current_user.id == comment.user_id %>
    <%= button_to "Destroy", post_comment_path(comment.post_id, comment.id), method: :delete, class: "block rounded-md text-red-500 px-2  py-2.5 text-[12px] font-medium  transition hover:bg-red-500 hover:text-white" %>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
<% if comment.errors.any? %>
<div>
  <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

  <ul>
    <% comment.errors.each do |error| %>
    <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div>
  <%= form.label :content, style: "display: block" %>
  <%= form.text_area :content %>
</div>

<div>
  <%= form.label :post_id, style: "display: block" %>
  <%= form.text_field :post_id, %>
</div>

<div>
  <%= form.submit%>
</div>
<% end %>

app/views/comments/_new.html.erb
<%= form_with model: [ post, Comment.new ] do |form| %>
<h1 class="font-bold"> Your comment:  </h1> <br>
<div>
    <%= form.text_field :user_id, value: current_user.id, type: "hidden" %>
</div>

<%= form.text_area :content, class: "w-full rounded-lg border-gray-200 align-top shadow-sm sm:text-sm mb-[30px]" %>
<%= form.submit class: "rounded-md bg-teal-600 px-5 py-2.5 text-sm font-medium text-white transition hover:bg-teal-700" %>



<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment  %> 
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"  class="text-center" ><%= notice %></p>

<h1 >Comments</h1>

<div id="comments" >
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<h1 >New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"  class="text-center"><%= notice %></p>
<%= render @comment %>

<div>

  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |

  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>

 
</div>